name: Sync Upstream

on:
  schedule:
    # 每天 UTC 时间 00:00 触发（可调整 cron 表达式）
    - cron: "0 0 * * *"
  workflow_dispatch: # 可选：允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取所有提交历史

      - name: 添加上游仓库
        run: |
          git remote add upstream ${{ github.event.repository.parent.html_url }}.git
          # 或手动指定上游 URL：
          # git remote add upstream https://github.com/上游用户/上游仓库.git

      - name: 拉取上游变更
        run: git fetch upstream

      - name: 合并到本地分支（例如 main）
        run: |
          git checkout main
          git merge upstream/main --no-edit
          # 如果存在冲突，此步骤会失败，需手动处理

      - name: 推送变更到复刻仓库
        run: git push origin main
